import './globals.css'
import type { Metadata } from 'next'
import { ptSerif, inter, baskervville, bebasNeue, novaSquare } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ptSerif.variable} ${inter.variable} ${baskervville.variable} ${bebasNeue.variable} ${novaSquare.variable}`}>
        {children}
      </body>
    </html>
  )
}
